[tool.poetry]
name = "oc-p2-scrap-books-online"
version = "0.1.0"
description = "Scrapping App"
authors = ["Nels-J"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
beautifulsoup4 = "^4.12.3"
requests = "^2.32.3"
flake8 = "^7.1.1"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
